function test(XData1, YData1, YData2, YData3, Parent1)
%CREATEFIGURE(XData1, YData1, YData2, YData3, Parent1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 28-Aug-2023 16:32:03

% Create figure
figure('Tag','ScopePrintToFigure',    'Color',[0.156862745098039 0.156862745098039 0.156862745098039],    'OuterPosition',[474 322 974 563]);
% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer();

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer();

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel();

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag');
hold(axes1,'on');
colororder([1 1 0.0666666666666667;0.0745098039215686 0.623529411764706 1;1 0.411764705882353 0.16078431372549;0.392156862745098 0.831372549019608 0.0745098039215686;0.717647058823529 0.274509803921569 1;0.0588235294117647 1 1;1 0.0745098039215686 0.650980392156863]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','y','Tag','DisplayLine1','LineWidth',0.75,'Color',[1 1 0.0666666666666667]);

% Create line
line(XData1,YData2,'DisplayName','Change in input','Tag','DisplayLine2','LineWidth',0.75,    'Color',[0.0745098039215686 0.623529411764706 1]);

% Create line
line(XData1,YData3,'DisplayName','θ^','Tag','DisplayLine3','LineWidth',0.75,'Color',[1 0.411764705882353 0.16078431372549]);

% Create xlabel
xlabel(' ');

% Create title
title('y, \hat{\theta}','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 20.0000000000001]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-22.9308675569954 9.25847356171957]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','Color',[0 0 0],'FontSize',8,    'GridAlpha',0.4,'GridColor',    [0.686274509803922 0.686274509803922 0.686274509803922],    'TickLabelInterpreter','none','XColor',    [0.686274509803922 0.686274509803922 0.686274509803922],'XGrid','on',    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'YGrid',    'on','ZColor',[0.686274509803922 0.686274509803922 0.686274509803922]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','pixels',    'TextColor',[0.882062358925529 0.882062358925529 0.882062358925529],    'Position',[817.333335568503 265.333332385575 125.999997764826 46.9999987483025],    'Interpreter','none',    'FontSize',8,    'EdgeColor',[0.882062358925529 0.882062358925529 0.882062358925529]);

% Create text
text('Tag','TimeOffsetStatus','Parent',Parent1,'Units','pixels',    'VerticalAlignment','bottom',    'FontSize',8,    'Position',[0 0 0],    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],    'Visible','on');

